local Tips = {
	"Back up Terry!",
	"Tanner is not allowed here.",
	"Why is this music fire tho?",
	"Insert SplashText.txt",
	"99 cents at the asteroid store!",
	"I dont think this is my college essay…..",
	"Work at a pizza place dosent have space battles!",
	"Git gud.",
	'ROBLOX!!!!11!!!',
	'Blow up ships!',
	'Get your grandma to play!',
	'Space Raiders (again!)',
	'The ost is free, ya know.',
	'The outlet is a lie.',
	'Office beanbag = naptime.',
	'This aint rocitizens!',
	'If you use tanners tone, you’re banned.',
	'If you use tanners tone, I will give you infinite wishes (real)',
	'1% milk',
	'Pear juice',
	"Also Try Michael's Zombies!",
	'Certified Pond owner.',
	'NOW THAT’S A LOT OF DAMAGE!',
	'Im going to eat Ben’s code',
	'My speakers are on fire!',
	'Ryan finished college in 30 minutes.',
	'Certified hood classic.',
	'oh yeah Mr Krabs, oh yeah oh yeah Mr Krabs',
	'feet.',
	'Dig Deep!',
	'This aint Minecraft……',
	'I THINK IM IN THE WRONG GAME!',
	'“Mickey mouse”',
	'YOUR MOM!',
	'Elden Ring time.',
	'The only game made exclusively after 1am!',
	'If you play at 3am, nothing special happens!',
	"Space Raiders was made in a 50-degree garage.",
	"I am rapidly approaching your location.",
	"Shoot ships. Bang bang.",
	"Run cleetus!",
	"*Milwaukee sirens*",
	"The shop is full of things to buy.",
	"The shop menu might have secrets (hint hint)",
	"Look for the amogus in the MyShip menu",
	"Get your dog to play?",
	"Get your cat to play?",
	"Harold.",
	"Cooper the indestructible is approaching your location",
	"I'm swiftly approaching your location.",
	"Tanner moment",
	"Ben approved!",
}

return Tips
